var GAME_LEVELS = [
  ["                                                                                       ",
   "                                                                                       ",
   "                                                                                       ",
   "                                                                                       ",
   "                                                                                       ",
   "                                              o o o              o   o                 ",
   "                                                                                       ",
   "                                             xxxxxxx    xxx     x!!!!!xx               ",
   "                                    o  o  o                     x!!!!!x                ",
   "                                                                x!!!!!x                ",
   "                                        xxxxx                   xxxxxxxxxxxxx        xx",
   "                                   xx                                                 x",
   "xx            o o                  xx       o o                      o                x",
   "x                        o         xxx                                                x",
   "x           xxxxxxx                xxx   xxxxx                      xxx        o      x",
   "x                       xxx        xxx          xxx                 xxx               x",
   "x @                     xxx        xxx                              xxx       xxxx    x",
   "xxxxxxxxxxxxxx   xxx  xxxxxxx      xxxxxxxxxxxxxxxxxxxx     xxxxxxx xxxxx   xxx     o x",
   "xxxxxxxxxxxxxx   xxx  xxxxxxx      x            o o   x     xxxxxxxxxxxxx   xxx       x",
   "xxxxxxxxxxxxxx   xxx  xxxxxxx      x o                x     xxxxxxxxxxxxx!|!xxx   xxxxx",
   "xxxxxxxxxxxvxx   xxx!!xxxxxxx!!!!!!x   xxx      xxx   x!|!|!xxxxxxxxxxxxx!!!xxx o     x",
   "x  o  o      x   xxx!!xxxxxxx!!!!!!x         x        x!!!!!xxxxxxxxxxxxxxxxxxx       x",
   "x            x   xxxxxxxxxxxxxxxxxxx                  xxxxxxxx              xxxxxx    x",
   "xxxxxxxxx        xxxxxxxxxxxxxxxxxxxxxx xxx                                         o x",
   "x           o  o x                                        o o                   o     x",
   "x                x      o                   xxx                              o    xxxxx",
   "xx       xxxxxxxxx                                      xxxxxxx           o    xxxxxxxx",
   "xxx     o  o           xxx                      xx                 o o o    xxxxxxxxxxx",
   "xxxx                   xxx                      xxxx                     xxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!|!xxx!|!xxx!!!xxxxxx!!|!!!!!!!!!|!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxx!!!xxx!!!xxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "  @                             o o o o o o                                              o o o                    ",
   "xxxxx                                                                                                             ",
   "                               xxxxxxxxxxxxx      cccccccccccccccccccccccccccccccc      xxxxxxx       o           ",
   "                                                                                                                  ",
   "                                                                                                    cccc          ",
   "                                                                                                            o  o  ",
   "            o o o                                                                                                 ",
   "                                                      o               o                                    xxxxxx ",
   "           xxxxxxx                                                                               o o              ",
   "                        cccc                         xxxcccccccccccccxxx                               cc         ",
   "                                       o o                                             o o      xxxxx             ",
   "                                                                                                                  ",
   " o o                              cccxxxxxxxccc                                       xxxxx                       ",
   "                                                                          o o     c                               ",
   "xxxxx                      cccc                                                                                   ",
   "                    o o                                                 xxxxxxx                                   ",
   "                                                                                                                  ",
   "                ccxxxxxxx                                    o o    cc                                            ",
   "                                                                                                                  ",
   "          cc                                               xxxxxxx                                                ",
   "                                                                                                                  ",
   "      cc                                                                                                        o ",
   "                                                                                                                  ",
   "xxxxxx !|!!!!|!              !!!|!!!!!!             !!|!!!!!!             !!!!!!!!!|              !!!!!!!!|!   ccc",
   "     !!!!!!!!!!!            !!!!!!!!!!!!           !!!!!!!!!!!           !!!!!!!!!!!!            !!!!!!!!!!!!     ",
   "    !!!!!!!!!!!!!!         !!!!!!!!!!!!!!         !!!!!!!!!!!!!         !!!!!!!!!!!!!!          !!!!!!!!!!!!!!    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|!|!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                  xxxxxxxxxxxx                                                                                    x",
   "x                 xxxxxxxxxx                                                                                       x",
   "x @           xxxxxxxxxxx                      o          o          o          o         o                        x",
   "xxxxxx       xxxxxxxxxx                                                                                            x",
   "x            xxxxxxx                          ccc        c c        cccc       c c        c                  xxxxxxx",
   "x         o  xxxxxx                  xxxxxxxx!!!!!xxxxxx!!!!!xxxxxx!!!!!!xxxxx!!!!!xxxxx!!!!!xxxxxxxxx             x",
   "x            xxxxx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x",
   "x        xxxxxxxx               xxxx                                                             xxxxxxxxxxxx      x",
   "x            xxx              xxx                                 o                                xxxxx           x",
   "x            xx              xx                                                                      xxx           x",
   "x o o o      x              xx                              xxxxxxxxxxxx                              xx      xxxxxx",
   "x            x+        o    xx                                                   xxx                  xx           x",
   "xxxxxxxx     x              xx               xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx               xx           x",
   "x            x    occc      xx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         o   xxxxxxxx     x",
   "x        o   x              xx      o   xxxxxxxx     c           c           c     xxxxxxx            xx           x",
   "x            x        o     xx           xxxvx                                   o   xxxxx  x         xx           x",
   "x    cc  o   xccc           xxx          xx                c           c              xxxx            xx     xxxxxxx",
   "x            x    o         xx   o       xx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xx           x",
   "x        o   x              xx          xxx   xx                                        xx   x        xx           x",
   "xcc          xcccccc   o cccxx           xx   xx                                        xx            xxxxxxx      x",
   "x            x              xxx      o   xx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xx            xx           x",
   "x            x              xx           xx   xx                                       cxx    x       xx           x",
   "x    xxx!|!xxx     occcc    xx   o      xxx   xx                                        xx            xx      xxxxxx",
   "x    xxxxxxxxx              xx           xx   xx           x   x   x   x   x   x   x  xxxx            xx           x",
   "x            x              xxx          xx   xx       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     x      xx           x",
   "x            x  o       ccccxx        o  xx   xx   c   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxx     x",
   "x            xcc        o   xx          xxx o xx                                        xx            xx           x",
   "x            x              xx   o       xxxxxxx                                        xx      x     xx           x",
   "xo           x   cccc o     xx           xxxxxxxx                                       xx            xx      xxxxxx",
   "xcccc        x              xxx          xxxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxx          xx            xx           x",
   "x!!!!x       x    o       ccxx            xxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxxx     o xx       x    xx           x",
   "xxxxxx       x              xx                                                          xx            xxxxxxxx     x",
   "x            x              xx                                                        xxxx        x   xx           x",
   "x            x         o    xxxx                                                o    xxxxx            xx       o o x",
   "x            x        ccc    xxxxx                                                 xxxxxxx         x  xx           x",
   "x            x               xxxxxxxxxxcccccccccc  c  cccccc ccccc ccc c c cxxxxxxxxxxxxxx            xx      x x xx",
   "x            xccccc           xxxxxxxxx!!!!!!!!!!|!!!|!!!!!!|!!!!!!!!!|!!!!!xxxxxxxxxxxxxx            xx           x",
   "x            x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxx           x",
   "x            x                                                                                        xx           x",
   "x      o o o x                                                                                        xxxxxxx      x",
   "x            x                                          o           o      o         o            xxxxxx       o o x",
   "x      xxxxxxxxxxx                                                                              xxxxxxxx          xx",
   "x            xxxxxxxxxxx                  xxx c                                               xxxxxxxxxx         xxx",
   "x             xxxxxxxxxxxxxxxx   !|!   xxxxxx!!!xxxxxxx!|!xxxxddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxx",
   "x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x",
   "x                                                                                                   xxxx           x",
   "x                                                                                                    xxxx          x",
   "x                             o   o     o   o     o   o     o   o     o   o     o   o                 xxxxx        x",
   "x                                                                                                                  x",
   "xxxxx                       cccccccccccccccccc  c c   c c c c c c   ccccccccccc cccc                           xxxxx",
   "xxxxxxxxxx          xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx          xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
